### ISSUE TITLE
Verkrijgen veilige ruimte voor Dissassembly van Batterijen

### ISSUE THREAD

**Issue by OlivierWesterman** [vives-project-xp/GreenhouseEnergy#25]
Om veilig te kunnen werken met de batterijen zouden we best een labolokaal, een brandblusser gemaakt voor Li vuur, handschoenen en veiligheidsbril.
Labolokaal kan gereserveerd worden via vives
Brandblusser moet naar gevraagd worden bij de leerkrachten
Handschoenen en veiligheidsbril neem je mee van thuis

**Comment by SampersS** [comment]
Email gestuurd naar de heer Calleeuw voor aanvraag labolokaal.

**Comment by SampersS** [comment]
Sinds we geen labo kunnen verkrijgen en we al een bak met water hebben zal ik dit issue sluiten.
