### ISSUE TITLE
Doorsturen stl files naar printer

### ISSUE THREAD

**Issue by OlivierWesterman** [vives-project-xp/GreenhouseEnergy#64]
We zullen in het totaal 13 brackets nodig hebben, elk met hun top en bottom deel uiteraard.
Stuur deze door naar mnr. Leroy en voeg de bestelling ervan toe aan de excel.

**Comment by joshuameuleman** [comment]
![image](https://github.com/user-attachments/assets/2cbd7d09-eb4e-441a-abe9-d26e311e1048)

**Comment by joshuameuleman** [comment]
Fotos toegevoegd
