### ISSUE TITLE
Lijst van mogelijke componenten opstellen

### ISSUE THREAD

**Issue by OlivierWesterman** [vives-project-xp/GreenhouseEnergy#9]
Als deel van de research, maak een lijst van opties met daarin mogelijkheden voor batterijen, laadregelaars, vermogensensoren, zonnepanelen. Deze lijst kan later uitegebreid worden indien nodig.

**Comment by joshuameuleman** [comment]
vermogensensor uitleg : https://www.eaton.com/us/en-us/products/controls-drives-automation-sensors/sensors---limit-switches/power-sensor.html

vermogenmeter met display
https://www.benselectronics.nl/oled-volt-ampere-vermogens-meter-voor-paneel-inbou.html

**Comment by SampersS** [comment]
componenten die we allesinds nodig hebben:
-micro controller: sensor inlezen en communicatie laad eenheid
-temperatuur sensor: per batterij, moet in design passen 
-spanning sensor: per batterij

**Comment by SampersS** [comment]
sinds we met redelijk wat cellen werken voorlopig gwn een stm32 gebruiken, wss gaan we dit dan ook nodig hebben in het uiteindelijke resultaat, reden: esp32 heeft wss niet genoeg gpio poorten
Ik neem volgende week wel mijn stm32 mee.

**Comment by SampersS** [comment]
<a href='https://www.otronic.nl/nl/ds18b20-to92-temperatuur-sensor-dallas-clone.html'>https://www.otronic.nl/nl/ds18b20-to92-temperatuur-sensor-dallas-clone.html</a>

Dit als temperatuur sensor?

**Comment by SampersS** [comment]
> vermogensensor uitleg : https://www.eaton.com/us/en-us/products/controls-drives-automation-sensors/sensors---limit-switches/power-sensor.html
> 
> vermogenmeter met display https://www.benselectronics.nl/oled-volt-ampere-vermogens-meter-voor-paneel-inbou.html

met de nieuwe vereiste van 48V zal dit niet meer gaan (spannings metingen tot 33V)
